### ISSUE TITLE
Overbright on brushes

### ISSUE THREAD

**Issue by GEEKiDoS** [thexa4/source-pbr#18]
![C9O3{N5I0K568N%)WMI1Z1A](https://user-images.githubusercontent.com/14933408/71479965-ce6d4e80-2831-11ea-96ea-47534c857bd3.png)

If I add $model 1 in the VMTs, overbright disappers, but the reflection is not working as expected
![$H)KUGGI1Q 9 $M3YNH XRC](https://user-images.githubusercontent.com/14933408/71480020-f78ddf00-2831-11ea-8651-0c4ce108902c.png)
![AEETG(9SG%V)PMGK_H AR37](https://user-images.githubusercontent.com/14933408/71480024-f8267580-2831-11ea-9f3b-d6345ad62e90.png)
Reflection will changes while player is moving

**Comment by thexa4** [comment]
From what I could understand from the source engine internals there is only one `env_cubemap` when rendering. This causes reflections to change while the user is moving.

You should be able to work around it by manually assigning a cubemap to use.

**Comment by thexa4** [comment]
Could likely have been fixed by #21

**Comment by YuRaNnNzZZ** [comment]
Sadly that PR didn't fix the issue.
`$model 0`:
![изображение](https://user-images.githubusercontent.com/5104603/74931579-ef48bf00-53f0-11ea-91f0-2e617ebe52da.png)
`$model 1` (envmap reflection bugs out when player moves around, just as described in this issue):
![изображение](https://user-images.githubusercontent.com/5104603/74931586-f4a60980-53f0-11ea-842c-517a635c17e2.png)

**Comment by sears2424** [comment]
this is what i have too about the normals acting weirdly.. im trying to determine what causes this.

**Comment by vakkendwarf** [comment]
is this fixed by using a custom $envmap?

**Comment by thexa4** [comment]
We have a new potential fix! Would you mind retrying with the latest version?

**Comment by GEEKiDoS** [comment]
> We have a new potential fix! Would you mind retrying with the latest version?

~That fix works!~ but without $model 1, the overbright is still exists

Sorry for my incomplete testing, this issue is not fixed, but it's much better than before

Here's a video: https://raw.githubusercontent.com/GEEKiDoS/mypage/master/pbrbug_1.mp4

**Comment by sears2424** [comment]
Judging from the video the brush gets the cubemap using the viewmodel / player position

**Comment by sears2424** [comment]
@GEEKiDoS Can you try making an entirely new map using the new shader?
https://cdn.discordapp.com/attachments/620975921888886824/700182707140820992/2020-04-16_11-15-37.mp4
i modified the map textures of the left wall and floor, left the catwalk untouched.

**Comment by RedstarDev** [comment]
GEEKiDoS, it looks like vrad is not baking lightmaps properly to your PBR wall texture during compile. 
As you can see from your grey dev texture on the floor which is most likely using the vanilla LightmappedGeneric shader, lightmaps are properly baked and you get a shadow there. This is most likely due to your compiler pointing to the wrong game folder, and therefor to the wrong shader. If you are using CompilePalX, make sure that inside of gameConfigs.json the "GameFolder" is pointing to the actual sourcemods' folder containing the PBR shader, not your own mod. If you're using hammer: tools-->options-->Game directory.

Another thing worth noting is that the shader only works properly with HDR and not LDR.
So make sure that mat_hdr_level is set to 2 when testing.

Let me know if that helps.

**Comment by GEEKiDoS** [comment]
Yes I already set my hammer setting to my mod that contains PBR shader, but it not works.
But now I changed all PBR to LightmappedGeneric during compiling, then change them back to PBR before running game, it is just working magically

**Comment by GEEKiDoS** [comment]
I found the issue is that I did't add ```"$envmap" "env_cubemap"``` to my material, the sample vmt on https://wiki.empiresmod.com/PBR also didn't have that
